# Generated by Django 4.0.3 on 2022-03-22 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_busquedablog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
