# Generated by Django 4.0.3 on 2022-04-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_imagen_alter_post_author_imagenpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images'),
        ),
        migrations.DeleteModel(
            name='ImagenPost',
        ),
    ]
