# Generated by Django 4.0.3 on 2022-04-14 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_imagen_delete_imagenpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.date.today),
        ),
    ]
