# Generated by Django 4.0.3 on 2022-04-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusquedaBlog',
        ),
    ]
