# Generated by Django 4.0.3 on 2022-03-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='image',
        ),
    ]
