# Generated by Django 4.0.3 on 2022-04-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
